const assert = require('node:assert/strict');
const values = new Map([['power-workspace-theme', 'ocean'], ['power-workspace-mode', 'dark']]);
global.localStorage = { getItem: key => values.get(key) || null, setItem: (key, value) => values.set(key, value) };
global.CustomEvent = class { constructor(type, init) { this.type = type; this.detail = init.detail; } };
const html = { dataset: {} };
const meta = { content: '' };
global.document = { documentElement: html, querySelector: selector => selector === 'meta[name="theme-color"]' ? meta : null, dispatchEvent() {} };
let systemListener; let systemDark = false;
global.matchMedia = () => ({ get matches() { return systemDark; }, addEventListener: (_, listener) => { systemListener = listener; } });
const Appearance = require('../public/ui/appearance.js');
assert.equal(Object.keys(Appearance.themes).length, 9);
assert.equal(html.dataset.theme, 'ocean');
assert.equal(html.dataset.mode, 'dark');
Appearance.setTheme('aurora');
assert.equal(values.get('power-workspace-theme'), 'aurora');
Appearance.setMode('system');
assert.equal(html.dataset.mode, 'light');
systemDark = true; systemListener();
assert.equal(html.dataset.mode, 'dark');
const previous = Appearance.theme;
Appearance.randomize(() => 0);
assert.notEqual(Appearance.theme, previous);
assert.equal(values.get('power-workspace-theme'), Appearance.theme);
